server:
  port: 8085

flyway.url: jdbc:mysql://localhost:3306/its_education_db
flyway.user: root
flyway.password: root
flyway.locations: filesystem:migrations/sql

spring: #Spring Configurations
  flyway:
    locations: filesystem:migrations/sql
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false # to prevent exception while serializing empty objects
  application:
    name: com-its-education
  jpa:
    show-sql: true
    properties:
      hibernate:
        #format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          time_zone: UTC
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource: #Datasource Configurations
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${flyway.url}
    username: ${flyway.user}
    password: ${flyway.password}
    max-active: 340
    initial-size: 50
    validationQuery: "SELECT 1"
    testOnBorrow: true
  mvc:
    throw-exception-if-no-handler-found: false

public:
  api-endpoints: api-docs,swagger-ui.html
  folders: swagger-resources,swagger-ui
logging:
  path: /tmp/haathi/logs/org-service
  file: ${logging.path}/org-service-api.log

thread:
  default:
    corePool-size: 10
    max-size: 10
    scheduler: # scheduler config 
      pool-size: 10
  queueCapacity: 300
 
retry:
  maxAttempts: 2
  delay: 2000
  multiplier: 2
  maxDelay: 9000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000 # 120Sec


